version: '3'

services:
  sqlserver_taskapp:
    container_name: sqlserver_taskapp
    image: mcr.microsoft.com/mssql/server
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1q2w3e4r@#$
    volumes:
      - taskapp_sqlserver_data:/mcr.microsoft.com/mssql/server

volumes:
  taskapp_sqlserver_data:
